---
# tasks file for ansible-role-jenkins

- include: "install_{{ ansible_os_family }}.yml"

- include: "configure_{{ ansible_os_family }}.yml"

- include: "install_plugins.yml"

- include: "job_setup.yml"

- name: Jenkins Service
  service:
    name: jenkins
    state: started
    enabled: yes
  become: yes
